create database sql_project;
use sql_project;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
sup_id TINYINT PRIMARY KEY,
sup_name VARCHAR(255),
address TEXT
);
-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
cat_id TINYINT PRIMARY KEY,
cat_name VARCHAR(255)
);
-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
emp_id TINYINT PRIMARY KEY,
emp_name VARCHAR(255),
hire_date VARCHAR(255)
);
-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
cust_id SMALLINT PRIMARY KEY,
cust_name VARCHAR(255),
address TEXT
);
-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
prod_id TINYINT PRIMARY KEY,
prod_name VARCHAR(255),
sup_id TINYINT,
cat_id TINYINT,
price DECIMAL(10,2),
FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
ON UPDATE CASCADE ON DELETE CASCADE
);
-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
ord_id SMALLINT PRIMARY KEY,
cust_id SMALLINT,
emp_id TINYINT,
order_date VARCHAR(255),
FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
ON UPDATE CASCADE ON DELETE CASCADE
);
-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
ord_id SMALLINT,
prod_id TINYINT,
quantity TINYINT,
each_price DECIMAL(10,2),
total_price DECIMAL(10,2),
FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (prod_id) REFERENCES products(prod_id)
ON UPDATE CASCADE ON DELETE CASCADE
);
select * from orders;

-- Analysis Questions
-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.
-- ● How many unique customers have placed orders?
select  distinct cust_id,cust_name from customers;
-- ● Which customers have placed the highest number of orders?
select cus.cust_id,cus.cust_name,count(ord.ord_id) as hightest_orders from customers as cus
join orders as ord
on cus.cust_id=ord.cust_id
join order_details as ord_i
on ord_i.ord_id=ord.ord_id
group by cus.cust_id,cus.cust_name
order by hightest_orders desc 
limit 1;
-- ● What is the total and average purchase value per customer?
select cus.cust_id,cust_name,sum(total_price) as total_price,avg(total_price) as average_price from customers as cus
join orders as ord
on cus.cust_id=ord.cust_id
join order_details as ord_i
on ord_i.ord_id=ord.ord_id
group by cus.cust_id,cus.cust_name;

-- ● Who are the top 5 customers by total purchase amount?
select cus.cust_id,cust_name,sum(total_price) as total_purchase from customers as cus
join orders as ord
on cus.cust_id=ord.cust_id
join order_details as ord_i
on ord.ord_id=ord_i.ord_id
group by cus.cust_id,cust_name
limit 5;
-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- ● How many products exist in each category?
select cat_name,sum(prod_id) as products_count from categories as cate
join products as ord
on cate.cat_id=ord.cat_id
group by cat_name;
-- ● What is the average price of products by category?
select cat_name,avg(each_price) as average_price from categories as cate
join products as pro
on cate.cat_id=pro.cat_id
join order_details as ord_i
on ord_i.prod_id=pro.prod_id
group by cat_name;
-- ● Which products have the highest total sales volume (by quantity)?
select prod.prod_id,prod.prod_name ,sum(quantity) as highest_quantity from products as prod
join order_details as pro
on prod.prod_id=pro.prod_id
group by prod.prod_id,prod.prod_name
order by highest_quantity desc ; 

-- ● What is the total revenue generated by each product?
select pro.prod_id,pro.prod_name,sum(ord_i.total_price) as revenue_genarated from categories as cate
join products as pro
on cate.cat_id=pro.cat_id
join order_details as ord_i
on ord_i.prod_id=pro.prod_id
group by pro.prod_id,pro.prod_name;
-- ● How do product sales vary by category and supplier?
select pro.prod_id,pro.prod_name,cate.cat_name,supp.sup_name,sum(ord_i.total_price) as total_sales from products as pro
join categories as cate
on pro.cat_id=cate.cat_id
join supplier as supp
on supp.sup_id=pro.sup_id
join order_details as ord_i
on ord_i.prod_id=pro.prod_id
group by pro.prod_id,pro.prod_name,cate.cat_name;
-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- ● How many orders have been placed in total?
select count(ord_id) as orders_placed from order_details;
-- ● What is the average value per order?
select ord_id,avg(total_price) as average_value from order_details
group by ord_id;
-- ● On which dates were the most orders placed?
select order_date,count(ord_id) as most_orders_placed from orders
group by order_date
order by most_orders_placed desc
limit 5;
-- ● What are the monthly trends in order volume and revenue?
SELECT YEAR(STR_TO_DATE(order_date, '%m/%d/%Y')) AS order_year,
       MONTH(STR_TO_DATE(order_date, '%m/%d/%Y')) AS order_month,
       COUNT(DISTINCT o.ord_id) AS total_orders,
       SUM(od.total_price) AS total_revenue
FROM orders AS o
JOIN order_details AS od
ON o.ord_id = od.ord_id
GROUP BY YEAR(STR_TO_DATE(order_date, '%m/%d/%Y')),
         MONTH(STR_TO_DATE(order_date, '%m/%d/%Y'))
ORDER BY order_year, order_month;
-- ● How do order patterns vary across weekdays and weekends?
SELECT 
    CASE
        WHEN DAYOFWEEK(o.order_date) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY day_type;
-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- ● How many suppliers are there in the database?
select sup_id,sup_name from supplier;
-- ● Which supplier provides the most products?
select supp.sup_id,sup_name,count(prod_id) as total_products from products as pro
join supplier as supp
on supp.sup_id=pro.sup_id
group by supp.sup_id,sup_name
order by total_products desc ;
-- ● What is the average price of products from each supplier?
select supp.sup_id,supp.sup_name,avg(each_price) as average_price from supplier as supp
join products as pro
on pro.sup_id=supp.sup_id
join order_details as ord_i
on ord_i.prod_id=pro.prod_id
group by supp.sup_id,supp.sup_name;

-- ● Which suppliers contribute the most to total product sales (by revenue)?
SELECT
    s.sup_name,
    SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p
ON s.sup_id = p.sup_id
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY s.sup_name
ORDER BY total_revenue DESC;
-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- ● How many employees have processed orders?
select distinct(count(emp_id)) as total_employees from employees;
-- ● Which employees have handled the most orders?
select emp.emp_id,emp_name,count(ord_id) as order_count from employees as emp
join orders as ord
on emp.emp_id=ord.emp_id
group by emp.emp_id,emp_name
order by order_count desc;
-- ● What is the total sales value processed by each employee?
select emp.emp_id,emp_name,sum(total_price) as total_sales from employees as emp
join orders as ord
on ord.emp_id=emp.emp_id
join order_details as ord_i
on ord_i.ord_id=ord.ord_id
group by emp.emp_id,emp_name;
-- ● What is the average order value handled per employee?
select emp.emp_id,emp_name,avg(total_price) as average_sales from employees as emp
join orders as ord
on ord.emp_id=emp.emp_id
join order_details as ord_i
on ord_i.ord_id=ord.ord_id
group by emp.emp_id,emp_name;

-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- ● What is the relationship between quantity ordered and total price?
SELECT
    quantity,
    SUM(total_price) AS total_sales
FROM order_details
GROUP BY quantity
ORDER BY quantity;
-- ● What is the average quantity ordered per product?
select pro.prod_id,prod_name,avg(quantity) as average_quantity from products as pro
join order_details as ord_i
on ord_i.prod_id=pro.prod_id
group by prod_id,prod_name;

-- ● How does the unit price vary across products and orders?
SELECT
    p.prod_name,
    od.ord_id,
    od.each_price
FROM products p
JOIN order_details od
ON p.prod_id = od.prod_id
ORDER BY p.prod_name, od.ord_id;